services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10

  order-service:
    build: ./services/order_service
    container_name: order-service
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
      ORDER_EXCHANGE: orders.topic
    depends_on:
      rabbitmq:
        condition: service_healthy

  payment-service:
    build: ./services/payment_service
    container_name: payment-service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
      ORDER_EXCHANGE: orders.topic
      PAYMENT_EXCHANGE: payments.topic
      PAYMENT_QUEUE: payment.order.created
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification-service:
    build: ./services/notification_service
    container_name: notification-service
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
      ORDER_EXCHANGE: orders.topic
      PAYMENT_EXCHANGE: payments.topic
      NOTIFICATION_ORDER_QUEUE: notification.order.events
      NOTIFICATION_PAYMENT_QUEUE: notification.payment.events
    depends_on:
      rabbitmq:
        condition: service_healthy
